DEFAULT_MATERIAL_ID = 1      
DEFAULT_TEMPERATURE = 70.0   
DEFAULT_PRESSURE = 0.0       

CAESAR_AUTO_CALC_FLOAT = -1.0101
CAESAR_AUTO_CALC_STR   = " -1.0101d0"

INDEX_TEMPERATURE_START = 19
INDEX_TEMPERATURE_END   = 27 
INDEX_PRESSURE_START    = 28
INDEX_PRESSURE_END      = 36 
INDEX_MATERIAL          = 11

MANDATORY_COLUMNS = [
    "FROM_NODE", "TO_NODE", "DX", "DY", "DZ", 
    "DIAMETER", "THICKNESS", "CORROSION", "INSULATION", "DENSITY",
    "BEND_PTR", "RESTRAINT_PTR", "VALVE_PTR"
]
